variables:
  # Variables are reference by $varName format
  #  - Variable referencing is case insensitive
  #  - Variables can be used in:
  #    - following variable declarations
  #    - backupsDirPath
  #    - gameConfigs[*].saveDirPath
  #    - gameConfigs[*].saveMap[*]  (value only)
  windowsUser: username
  steamID: xxxxxxxxxxxxxxxxx
  steam3ID: xxxxxxxxx
  ubisoftID: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
  AppData: C:\Users\$windowsUser\AppData

# Parent directory where all backups will be saved is subdirectories.
backupsDirPath: C:\Users\$windowsUser\OneDrive\Backups\GameSaves

gameConfigs:
  # Each config must define:
  #  - shortName:       a reference name passed to the parameter -g, --game
  #  - fullName:        fancy name used in output messages
  #  - backupDirName:   name of the subdirectory in 'backupsDirPath' to store created backups (Created if doesn't exist)
  #  - saveDirPath:     directory containing game saves to backup
  #  - backupMethod:    all | map | listf | listd  (consult README.md for more information)
  #       - all:    backup whole directory or file defined in 'saveDirPath'
  #       - map:    backup a directory or file further specified in 'saveMap'.   saveDirPath/saveMap[`key`]  where `key` is provided by -s, --save parameter
  #       - listd:  backup a subdirectory located in 'saveDirPath'. param -s, --save specifies which subdirectory
  #       - listf:  backup a file located in 'saveDirPath'. param -s, --save specifies which file
  #
  #  - saveMap:         required for backup method 'map'
  #  - savePattern:     optional, used by backup methods 'listd' and 'listf'. Regex pattern to filter files/directories.

  - shortName: factorio
    fullName: Factorio
    backupDirName: Factorio
    saveDirPath: $AppData\Roaming\Factorio\saves
    backupMethod: listf
    savePattern: ^(?!_autosave).+\.zip$

  - shortName: nms
    fullName: No Man's Sky
    backupDirName: NoMansSky
    saveDirPath: $AppData\Roaming\HelloGames\NMS\st_$steamID
    backupMethod: all

  - shortName: forest
    fullName: The Forest
    backupDirName: TheForest
    saveDirPath: $AppData\LocalLow\SKS\TheForest\$steamID
    backupMethod: map
    saveMap:
      sp1: Singleplayer\Slot1
      sp2: Singleplayer\Slot2
      sp3: Singleplayer\Slot3
      sp4: Singleplayer\Slot4
      sp5: Singleplayer\Slot5
      mp1: Multiplayer\Slot1
      mp2: Multiplayer\Slot2
      mp3: Multiplayer\Slot3
      mp4: Multiplayer\Slot4
      mp5: Multiplayer\Slot5

  - shortName: mc
    fullName: Minecraft
    backupDirName: Minecraft
    saveDirPath: $AppData\Roaming\.minecraft\saves
    backupMethod: listd
    #savePattern: ''

  - shortName: mcs
    fullName: Minecraft Server
    backupDirName: Minecraft
    saveDirPath: C:\Users\$windowsUser\OneDrive\Personal\MCserver
    backupMethod: map
    saveMap:
      roboworld: roboworld

  - shortName: terraria
    fullName: Terraria
    backupDirName: Terraria
    saveDirPath: C:\Program Files (x86)\Steam\userdata\$steam3ID\105600
    backupMethod: all

  - shortName: ac1
    fullName: Assassin's Creed 1
    backupDirName: AssassinsCreed
    saveDirPath: $AppData\Roaming\Ubisoft\Assassin's Creed\Saved Games
    backupMethod: all

  - shortName: ac2
    fullName: Assassin's Creed 2
    backupDirName: AssassinsCreed
    saveDirPath: >-
      C:\Program Files (x86)\Ubisoft\Ubisoft Game
      Launcher\savegames\$ubisoftID\4
    backupMethod: all

  - shortName: oca
    fullName: Overcooked All you can eat
    backupDirName: Overcooked
    saveDirPath: $AppData\LocalLow\Team17\Overcooked All You Can Eat\$steamID
    backupMethod: all

  - shortName: oc2
    fullName: Overcooked 2
    backupDirName: Overcooked
    saveDirPath: $AppData\LocalLow\Team17\Overcooked2\$steamID
    backupMethod: all
